# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/curie/studio/zhuque

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/curie/studio/zhuque

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curie/studio/zhuque/CMakeFiles /home/curie/studio/zhuque/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curie/studio/zhuque/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zhuque

# Build rule for target.
zhuque: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zhuque
.PHONY : zhuque

# fast build rule for target.
zhuque/fast:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/build
.PHONY : zhuque/fast

ipv6upper.o: ipv6upper.cpp.o

.PHONY : ipv6upper.o

# target to build an object file
ipv6upper.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/ipv6upper.cpp.o
.PHONY : ipv6upper.cpp.o

ipv6upper.i: ipv6upper.cpp.i

.PHONY : ipv6upper.i

# target to preprocess a source file
ipv6upper.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/ipv6upper.cpp.i
.PHONY : ipv6upper.cpp.i

ipv6upper.s: ipv6upper.cpp.s

.PHONY : ipv6upper.s

# target to generate assembly for a file
ipv6upper.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/ipv6upper.cpp.s
.PHONY : ipv6upper.cpp.s

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/main.cpp.s
.PHONY : main.cpp.s

tcpclient.o: tcpclient.cpp.o

.PHONY : tcpclient.o

# target to build an object file
tcpclient.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpclient.cpp.o
.PHONY : tcpclient.cpp.o

tcpclient.i: tcpclient.cpp.i

.PHONY : tcpclient.i

# target to preprocess a source file
tcpclient.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpclient.cpp.i
.PHONY : tcpclient.cpp.i

tcpclient.s: tcpclient.cpp.s

.PHONY : tcpclient.s

# target to generate assembly for a file
tcpclient.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpclient.cpp.s
.PHONY : tcpclient.cpp.s

tcpexample.o: tcpexample.cpp.o

.PHONY : tcpexample.o

# target to build an object file
tcpexample.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpexample.cpp.o
.PHONY : tcpexample.cpp.o

tcpexample.i: tcpexample.cpp.i

.PHONY : tcpexample.i

# target to preprocess a source file
tcpexample.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpexample.cpp.i
.PHONY : tcpexample.cpp.i

tcpexample.s: tcpexample.cpp.s

.PHONY : tcpexample.s

# target to generate assembly for a file
tcpexample.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/tcpexample.cpp.s
.PHONY : tcpexample.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/zhuque.dir/build.make CMakeFiles/zhuque.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... zhuque"
	@echo "... ipv6upper.o"
	@echo "... ipv6upper.i"
	@echo "... ipv6upper.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tcpclient.o"
	@echo "... tcpclient.i"
	@echo "... tcpclient.s"
	@echo "... tcpexample.o"
	@echo "... tcpexample.i"
	@echo "... tcpexample.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

